feature: full screen onboarding
argentlabs/argent-x pull request #1234
Opened 2022-09-27 09:41 UTC by simonheys

2022-09-28 09:01 UTC, dhruvkelawala commented
Is this PR ready for review?

2022-10-05 11:06 UTC, dhruvkelawala requested changes

2022-10-05 11:06 UTC, dhruvkelawala commented on packages/extension/src/ui/features/onboarding/ui/OnboardingButton.tsx
> +import styled from "styled-components"
Should this be in a separate file? I think it can be in the same file. wdyt?

2022-10-05 11:06 UTC, dhruvkelawala commented on packages/extension/src/ui/routes.ts
> +  onboardingRestorePassword: route("/onboarding/restore/password"),
Better idea would be refactor them into a different object `onboardingRoutes` and then merge them here using spread

2022-10-05 11:25 UTC, dhruvkelawala commented
Other than these minor changes, things look good

2022-10-05 12:32 UTC, simonheys commented on packages/extension/src/ui/features/browser/tabs.ts
> -  const [isInTab, setIsInTab] = useState(false)
Yes because the initialisation is async so it is `undefined` when the state is 'not yet known'.

2022-10-05 12:34 UTC, simonheys commented on packages/extension/src/ui/features/onboarding/ui/OnboardingButton.tsx
> +import styled from "styled-components"
I think the buttons need a proper holistic refactor as part of the wider design system changes. This is pretty unique to Onboarding right now and I think better not to pollute the more general Button class with it.

2022-10-05 12:39 UTC, simonheys commented on packages/extension/src/ui/routes.ts
> +  onboardingRestorePassword: route("/onboarding/restore/password"),
Good point I agree there are better ways to declare the routing overall. However this is consistent with current approach for now, and I don't think we should introduce a new way of doing it as part of this PR.

2022-10-05 16:11 UTC, simonheys commented on packages/extension/src/ui/features/browser/tabs.ts
> -  const [isInTab, setIsInTab] = useState(false)
`false` implies 'definitely not in a tab', but as this is async initially we don't know if we are in a tab or not and should wait for a definite `true` or `false` state if we have to be definite. There is some part of the onboarding where this distinction matters though I can't remember where right now :) I'll go back and review it tomorrow to make sure it's clearer.

2022-10-06 09:11 UTC, simonheys commented on packages/extension/src/ui/features/browser/tabs.ts
> -  const [isInTab, setIsInTab] = useState(false)
On investigation, the onboarding ended up not using this hook after all. Have reverted the change

2022-10-06 09:27 UTC, dhruvkelawala approved these changes

2022-10-06 09:31 UTC, merged