BLO-549
argentlabs/argent-x pull request #1403
Opened 2022-11-08 11:18 UTC by bluecco

when switching network, keeps the current account if it exist on the network
otherwise, open the first account

2022-11-09 08:50 UTC, simonheys commented on packages/extension/src/ui/features/accounts/switchAccount.ts
> +      selectedAccount: existingAccoutnOnNetwork || visibleAccountsOnNetwork[0],
```suggestion
      selectedAccount: existingAccountOnNetwork || visibleAccountsOnNetwork[0],
```

2022-11-09 08:51 UTC, simonheys commented on packages/extension/src/shared/wallet.service.ts
> +    console.error("~ addressesEquals", e)
Is this console.error needed?

2022-11-09 08:53 UTC, simonheys commented on packages/extension/src/shared/wallet.service.ts
> +export const addressesEquals = (a: BaseWalletAccount, b: BaseWalletAccount) => {
Since we already have a function elsewhere called `isEqualAddress`, I think we should differentiate this better and maybe call it `isEqualWalletAddress` or something like that, just so the use case is clear it's about wallets

2022-11-09 08:54 UTC, simonheys commented on packages/extension/src/shared/wallet.service.ts
> +      BigNumber.from(b.address.toLowerCase()),
Could this use the existing `isEqualAddress` function, or is different and special somehow?

2022-11-09 08:56 UTC, simonheys commented
Small thing, can change the PR name to conventional commits style so something like 'feat: remember last selected account on network'

2022-11-09 09:21 UTC, simonheys commented on packages/extension/e2e/switchNetwork.test.ts
> +  const { address: address1_localhost } = await setupNewAccountWithTestnetEth(
I don't think the code uses `snake_case` anywhere else (unless it's for contract methods or API keys which are outside our control) so `address1_localhost` -> `address1Localhost` or `localhostAddress1` would be more consistent here

2022-11-09 09:22 UTC, simonheys requested changes
Works for me, added a few comments about style and typos

2022-11-10 11:58 UTC, bluecco commented on packages/extension/src/shared/wallet.service.ts
> +      BigNumber.from(b.address.toLowerCase()),
I wasn't aware of `isEqualAddress` :)
so I divided just moved this part out from `accountsEqual`

2022-11-10 12:01 UTC, bluecco commented on packages/extension/src/shared/wallet.service.ts
> +    console.error("~ addressesEquals", e)
I just kept the error when I divided the function
but I can remove it, what do you think?

2022-11-10 12:02 UTC, bluecco commented
@simonheys pr updated

2022-11-10 14:12 UTC, simonheys approved these changes

2022-11-10 14:16 UTC, merged