chore: extract guardian logic in its own package
argentlabs/argent-x pull request #1657
Opened 2023-01-23 17:46 UTC by bluecco

### Issue / feature description

Move guardian logic in its own package

### Changes

Moved all the logic and files used by guardian in `guardian` package

### Checklist

- [ ] Rebased to the last commit of the target branch (or merged)
- [ ] Code self-reviewed
- [ ] Code self-tested
- [ ] Tests updated (if needed)
- [ ] All tests are passing locally

Please keep your pull request as small as possible. If you need to make multiple changes, please create separate pull requests for each change. Create a draft pull request if you need early feedback. This will mark the pull request as a work in progress and prevent it from being reviewed or merged until you are ready.

Please move drafts to the ready for review (regular PR) when you are ready to start the review process and other developers will pick it up from there.

2023-01-23 17:46 UTC, bluecco commented
@janek26 @simonheys this is how I've proceeded in order to have guardian in its own package

@simonheys maybe we can check together how to test that everything is ok

2023-01-25 12:02 UTC, simonheys commented on packages/guardian/package.json
> +  "version": "6.0.1",
```suggestion
  "version": "5.2.0",
```

2023-01-25 12:02 UTC, simonheys commented on packages/extension/package.json
> +    "@argent/guardian": "^6.0.1",
```suggestion
    "@argent/guardian": "^5.2.0",
```

2023-01-25 12:03 UTC, simonheys commented on packages/guardian/.gitignore
> +# Logs
This whole file can be removed unless its specifying something other than what's in the root `.gitignore`?

2023-01-25 12:04 UTC, bluecco commented on packages/guardian/.gitignore
> +# Logs
useless, will remove

2023-01-25 12:04 UTC, bluecco commented on packages/guardian/package.json
> +  "version": "6.0.1",
right, I was starting from web wallet at the beginning

2023-01-25 12:05 UTC, simonheys commented on packages/guardian/package.json
> +    "starknet": "^4.19.2"
This is specified in both dev and peer -  should be one or the other?

2023-01-25 12:09 UTC, bluecco commented on packages/guardian/package.json
> +    "starknet": "^4.19.2"
will remove get-starknet-core, not used

2023-01-25 12:11 UTC, simonheys commented on packages/guardian/src/services/account.ts
> +export const ARGENT_API_BASE_URL = process.env.ARGENT_API_BASE_URL as string
I feel that `ARGENT_API_BASE_URL` and `cosignerSign` implementations are specific to the extension. e.g. the original fetcher method of cosignerSign also includes some version headers that are expected.

How about moving the types `Cosigner, CosignerMessage` into `GuardianSigner.ts` where they are referenced, then move the actual `cosignerSign` implementation back into the extension?

2023-01-25 12:14 UTC, bluecco commented on packages/guardian/src/services/account.ts
> +export const ARGENT_API_BASE_URL = process.env.ARGENT_API_BASE_URL as string
works for me, I can always change that later if needed to be shared

2023-01-25 12:21 UTC, janek26 commented on packages/guardian/src/services/idb.ts
> -import Dexie, { Table } from "dexie"
I'm not sure if we should keep this in shared, or if we should move everything storage out of this shared package, and just export a StorageInterface ?

2023-01-25 12:26 UTC, simonheys commented on packages/guardian/src/services/idb.ts
> -import Dexie, { Table } from "dexie"
I agree to move it out of shared, the use case seems slightly different.

2023-01-25 12:52 UTC, bluecco commented on packages/guardian/src/services/idb.ts
> -import Dexie, { Table } from "dexie"
👍

2023-01-25 13:19 UTC, bluecco commented on packages/guardian/src/services/account.ts
> +export const ARGENT_API_BASE_URL = process.env.ARGENT_API_BASE_URL as string
also @simonheys , for ARGENT_API_BASE_URL, I'll add the url in `cosignerSign`

resulting into `export const cosignerSign: Cosigner = async (url: string, message: CosignerMessage) => {...}`

2023-01-26 09:09 UTC, simonheys commented on packages/guardian/src/services/idb.ts
> -import Dexie, { Table } from "dexie"
Works well!

2023-01-26 09:10 UTC, simonheys commented on packages/guardian/package.json
> +    "@tsconfig/svelte": "^3.0.0",
This package is not using Svelte? Could simplify by removing this and maybe using same tsconfig from similar package - maybe multicall package?

2023-01-26 09:12 UTC, simonheys requested changes
Works great - just one final comment on config then good to merge

2023-01-26 09:47 UTC, simonheys approved these changes

2023-01-26 09:49 UTC, merged