Blo 690
argentlabs/argent-x pull request #1780
Opened 2023-02-20 10:44 UTC by diegodelrieu

### Issue / feature description

Form for multisig creation (without backend call)

2023-02-20 11:32 UTC, dhruvkelawala requested changes

2023-02-20 11:32 UTC, dhruvkelawala commented on packages/extension/scripts/hot-reload-server.ts
> +import { debounce } from "lodash"
Why?

2023-02-20 11:32 UTC, dhruvkelawala commented on packages/extension/src/ui/features/accounts/multisig/CreateMultisigScreen/index.tsx
> +`
We are moving away from styled-components and sticking with chakra-ui & argent-ui for everything new

2023-02-20 11:46 UTC, dhruvkelawala commented
<img width="949" alt="Screenshot 2023-02-20 at 11 44 15" src="https://user-images.githubusercontent.com/50968441/220097442-4abdf633-c59e-4215-b86d-298db6b0d58c.png">

I think it's better to validate "incorrect signer" on submit (not onBlur), because user might be waiting for other signers and I don't think we should show error message at that time

2023-02-20 12:27 UTC, diegodelrieu commented on packages/extension/src/ui/features/accounts/multisig/CreateMultisigScreen/index.tsx
> +`
Ok yeah this was just lazy copy pasta from a similar page but will migrate to chakra

2023-02-21 10:39 UTC, dhruvkelawala approved these changes

2023-02-21 10:57 UTC, merged