[BLO-820] Users can fill in a multisig creation form [API logic]
argentlabs/argent-x pull request #1787
Opened 2023-02-21 10:48 UTC by diegodelrieu

### Issue / feature description

`Second half of the multisig creation ticket: actually create the multisig account locally.`

### Changes

- Add the necessary messages
- Refacto the components to make them smaller and more readable

### Checklist

- [x] Rebased to the last commit of the target branch (or merged)
- [x] Code self-reviewed
- [x] Code self-tested
- [x] Tests updated (if needed)
- [x] All tests are passing locally

Please keep your pull request as small as possible. If you need to make multiple changes, please create separate pull requests for each change. Create a draft pull request if you need early feedback. This will mark the pull request as a work in progress and prevent it from being reviewed or merged until you are ready.

Please move drafts to the ready for review (regular PR) when you are ready to start the review process and other developers will pick it up from there.

2023-02-21 11:06 UTC, dhruvkelawala requested changes
Lgtm otherwise

2023-02-21 11:06 UTC, dhruvkelawala commented on packages/extension/src/background/accountMessaging.ts
> +        )
Creating new multisig Message type will also solve this as signers and threshold will always be present for multisig accounts

2023-02-21 15:10 UTC, dhruvkelawala commented on packages/extension/src/background/accountMessaging.ts
> +
Console logs here

2023-02-21 15:10 UTC, dhruvkelawala commented on packages/extension/src/ui/features/accounts/multisig/CreateMultisigScreen/ScreenLayout.tsx
> +        <Panel> {/* <LogoSvg /> */}</Panel>
Commented code

2023-02-21 15:15 UTC, dhruvkelawala commented on packages/extension/src/ui/features/accounts/multisig/CreateMultisigScreen/MultisigSecondStep.tsx
> +      }
Can we handle error here properly? Something like "Unable to create Multisig right now. Please try again later"

2023-02-21 15:44 UTC, diegodelrieu commented on packages/extension/src/ui/features/accounts/multisig/CreateMultisigScreen/MultisigSecondStep.tsx
> +      }
we are, the hook is exposing isError and we're displaying a generic error when it's true

2023-02-21 15:44 UTC, diegodelrieu commented on packages/extension/src/ui/features/accounts/multisig/CreateMultisigScreen/ScreenLayout.tsx
> +        <Panel> {/* <LogoSvg /> */}</Panel>
oops

2023-02-22 11:00 UTC, simonheys commented on packages/extension/src/ui/features/accounts/multisig/CreateMultisigScreen/MultisigFirstStep.tsx
> +          + Add another owner
Instead of using `+` as text should use `leftIcon={<AddIcon />}` prop on `Button` component, where `AddIcon` is from the ui library icons

2023-02-22 11:01 UTC, simonheys commented on packages/extension/src/ui/features/accounts/multisig/CreateMultisigScreen/MultisigFirstStep.tsx
> +import { icons } from "@argent/ui"
Consolidate these two imports from same lib

2023-02-22 11:14 UTC, simonheys commented on packages/extension/src/ui/features/accounts/multisig/CreateMultisigScreen/MultisigFirstStep.tsx
> +          className={errors?.signerKeys?.[-1]?.key ? "error" : ""}
Should use chakra `Input` from ui library which as `isInvalid` prop to show error state

2023-02-22 11:18 UTC, simonheys commented on packages/extension/src/ui/features/accounts/multisig/CreateMultisigScreen/MultisigFirstStep.tsx
> +              <FormError>{errors.signerKeys?.[index]?.key?.message}</FormError>
Should use `FieldError` from ui library

2023-02-22 11:21 UTC, simonheys commented on packages/extension/src/ui/features/accounts/multisig/CreateMultisigScreen/MultisigThirdStep.tsx
> +          <TickCircleIcon color="#3ED373" alignSelf="flex-end" ml="1" />
```suggestion
          <TickCircleIcon color="success.500" alignSelf="flex-end" ml="1" />
```

2023-02-22 11:23 UTC, simonheys commented on packages/extension/src/ui/features/accounts/multisig/CreateMultisigScreen/useCreateMultisigForm.ts
> +        key: z.string().regex(/^[a-zA-Z0-9]{43}$/, "Incorrect signer key"),
Is this to validate base48? Can be more strict if so I suspect?

2023-02-22 11:51 UTC, simonheys commented on packages/extension/src/ui/features/accounts/multisig/CreateMultisigScreen/MultisigFirstStep.tsx
> +}
Feel like this should be part of UI library, wdyt

2023-02-22 11:53 UTC, simonheys commented on packages/extension/src/ui/features/accounts/multisig/CreateMultisigScreen/MultisigSecondStep.tsx
> +                    >
Can use Button size=lg here?

https://63484428a92aaaa11446b65b-vwazhqptnl.chromatic.com/?path=/story/components-button--danger&args=colorScheme:primary;size:lg

2023-02-22 14:00 UTC, dhruvkelawala commented on packages/extension/src/ui/features/accounts/multisig/CreateMultisigScreen/useCreateMultisigForm.ts
> +        key: z.string().regex(/^[a-zA-Z0-9]{43}$/, "Incorrect signer key"),
Yes, it's for base58 and I think it's right

2023-02-22 14:02 UTC, dhruvkelawala commented on packages/extension/src/ui/features/accounts/multisig/CreateMultisigScreen/MultisigSecondStep.tsx
> +      }
Right, my bad

2023-02-22 14:31 UTC, dhruvkelawala commented
My bad, please ignore

2023-02-22 14:49 UTC, diegodelrieu commented on packages/extension/src/ui/features/accounts/multisig/CreateMultisigScreen/useCreateMultisigForm.ts
> +        key: z.string().regex(/^[a-zA-Z0-9]{43}$/, "Incorrect signer key"),
I'm not sure how to make it more strict though

2023-03-02 16:34 UTC, simonheys commented on packages/extension/src/ui/features/accounts/multisig/CreateMultisigScreen/MultisigSecondStep.tsx
> +                    borderRadius={2}
```suggestion
                    borderRadius={'lg'}
```

radius use different tokens; we are still using defaults here https://github.com/chakra-ui/chakra-ui/blob/main/packages/components/theme/src/foundations/radius.ts

2023-03-02 16:35 UTC, simonheys commented on packages/extension/src/ui/features/accounts/multisig/CreateMultisigScreen/MultisigSecondStep.tsx
> +                      borderRadius="90"
```suggestion
                      borderRadius="full"
```

2023-03-02 16:36 UTC, simonheys approved these changes

2023-03-03 09:53 UTC, dhruvkelawala approved these changes

2023-03-03 09:53 UTC, merged