[BLO-769] Make wait time dynamic to speed up QA and testing work
argentlabs/argent-x pull request #1844
Opened 2023-02-28 10:40 UTC by diegodelrieu

### Issue / feature description

` Make wait time dynamic to speed up QA and testing work

2023-02-28 11:12 UTC, simonheys commented on packages/extension/.env.example
> +#WAIT_TIME=
Would prefer a more verbose name - wait time for what?

2023-02-28 12:01 UTC, dhruvkelawala commented on packages/extension/.env.example
> +#WAIT_TIME=
Agree

2023-02-28 12:05 UTC, dhruvkelawala commented on packages/extension/.env.example
> +#WAIT_TIME=
It's a common term even used in [ethers.js](https://docs.ethers.org/v5/api/providers/provider/#BaseProvider)

2023-02-28 16:15 UTC, janek26 requested changes
does this fix the issue @canlopes is having?
This would require him to always have an "QA" build with an custom env var, not applicable to RCs

I think you should return the inflight transactions from `transactionTracker.update` instead of just a flag which indicates if there are inflight transactions.
Once done, we can calculate that flag in the method plus additionally check if there are any transactions targeting network with id `localhost`. If so, then we can acceleratepolling (aka decrease waiting time between runs)

2023-03-02 09:55 UTC, diegodelrieu commented
> does this fix the issue @canlopes is having? This would require him to always have an "QA" build with an custom env var, not applicable to RCs
> 
> I think you should return the inflight transactions from `transactionTracker.update` instead of just a flag which indicates if there are inflight transactions. Once done, we can calculate that flag in the method plus additionally check if there are any transactions targeting network with id `localhost`. If so, then we can acceleratepolling (aka decrease waiting time between runs)

Thanks ! I think this is better now ?

2023-03-03 11:52 UTC, canlopes approved these changes

2023-03-07 17:02 UTC, janek26 approved these changes

2023-03-07 17:03 UTC, merged