Blo 696
argentlabs/argent-x pull request #1956
Opened 2023-03-24 14:40 UTC by diegodelrieu

### Issue / feature description

`Quick description of the issue or the feature that is implemented in the pr ie: add new transitions between screens`

### Changes

`quick list regarding the related changes within the pr`

ie:

- add new transaction transformer
- add new ui

### Checklist

- [ ] Rebased to the last commit of the target branch (or merged)
- [ ] Code self-reviewed
- [ ] Code self-tested
- [ ] Tests updated (if needed)
- [ ] All tests are passing locally

Please keep your pull request as small as possible. If you need to make multiple changes, please create separate pull requests for each change. Create a draft pull request if you need early feedback. This will mark the pull request as a work in progress and prevent it from being reviewed or merged until you are ready.

Please move drafts to the ready for review (regular PR) when you are ready to start the review process and other developers will pick it up from there.

2023-03-24 15:31 UTC, simonheys commented on packages/extension/src/ui/features/accountActivity/PendingMultisigTransactions.tsx
>              // TODO
Needed?
```suggestion
```

2023-03-24 15:36 UTC, simonheys commented on packages/extension/src/ui/features/multisig/hooks/useMultisigPendingTransaction.ts
> +      console.log(pendingTransactions)
```suggestion
```

2023-03-24 15:37 UTC, simonheys commented on packages/extension/src/ui/features/multisig/hooks/useMultisigPendingTransaction.ts
> +  const [pendingTransaction, setPendingTransaction] = useState<
Could use `useSWR` pattern for this - calling async function and storing in state?

2023-03-24 15:38 UTC, simonheys commented on packages/extension/src/ui/features/multisig/hooks/useMultisigRequest.ts
> +  return useSWR([account?.address, "multisigRequest", requestId], async () => {
Instead of account?.address there's some fn called `getAccountIdentifier()` that also includes the account network

2023-03-29 04:26 UTC, dhruvkelawala requested changes

2023-03-29 04:26 UTC, dhruvkelawala commented on packages/extension/src/ui/features/multisig/hooks/useMultisigPendingTransaction.ts
> +  })
```suggestion
  return useSWR(requestId, async () => {
    if(!requestId) {
        return
    }
  
    const pendingTransactions = await getMultisigPendingTransactions()
    const pendingTransaction = pendingTransactions.find(
      (transaction) => transaction.requestId === requestId,
    )
    return pendingTransaction
  })
```
Maybe?

2023-03-29 04:26 UTC, dhruvkelawala commented on packages/extension/src/ui/features/multisig/TransactionConfirmationsScreen.tsx
> +              {approvedSignersPublicKey.find((key) => key === signerKey) && (
```suggestion
              {approvedSignersPublicKey.some((key) => key === signerKey) && (
```
I would use `some` here but `find` works too

2023-03-29 04:26 UTC, dhruvkelawala commented on packages/extension/src/ui/features/multisig/hooks/useMultisigRequest.ts
> +        ),
```suggestion
        networkId: networkToStarknetNetwork(account.network),
```

2023-03-29 04:26 UTC, dhruvkelawala commented on packages/extension/src/ui/features/multisig/hooks/useMultisigRequest.ts
> +} from "../../../../shared/utils/starknetNetwork"
```suggestion
import {
networkToStarknetNetwork
} from "../../../../shared/utils/starknetNetwork"
```

2023-03-31 06:34 UTC, dhruvkelawala approved these changes

2023-03-31 09:51 UTC, merged