remove signer from multisig
argentlabs/argent-x pull request #1963
Opened 2023-03-27 13:42 UTC by diegodelrieu

### Issue / feature description

`Quick description of the issue or the feature that is implemented in the pr ie: add new transitions between screens`

### Changes

`quick list regarding the related changes within the pr`

ie:

- add new transaction transformer
- add new ui

### Checklist

- [ ] Rebased to the last commit of the target branch (or merged)
- [ ] Code self-reviewed
- [ ] Code self-tested
- [ ] Tests updated (if needed)
- [ ] All tests are passing locally

Please keep your pull request as small as possible. If you need to make multiple changes, please create separate pull requests for each change. Create a draft pull request if you need early feedback. This will mark the pull request as a work in progress and prevent it from being reviewed or merged until you are ready.

Please move drafts to the ready for review (regular PR) when you are ready to start the review process and other developers will pick it up from there.

2023-03-29 04:44 UTC, dhruvkelawala requested changes

2023-03-29 04:44 UTC, dhruvkelawala commented on packages/extension/src/background/transactions/transactionMessaging.ts
> +          }),
```suggestion
          calldata: stark.compileCalldata({
            new_threshold: newThreshold.toString(),
            signers_to_remove: utils.hexlify(
              utils.base58.decode(signerToRemove),
            ),
          }),
```

Don't need to add `*_len`

2023-03-29 04:44 UTC, dhruvkelawala commented on packages/extension/src/shared/call/changeMultisigSignersCall.ts
> +      validateAndParseAddress(call.contractAddress)
```suggestion
      validateAndParseAddress(call.contractAddress)
```
This seems better https://github.com/argentlabs/argent-x/blob/bb5d62371cedfa90f6876f207985b74a1d9515c2/packages/extension/src/ui/services/addresses.ts#L76

2023-03-29 04:44 UTC, dhruvkelawala commented on packages/extension/src/ui/features/multisig/MultisigOwnersScreen.tsx
> +                    px="1em"
Why using `em` units? I think it's better to just using `px={1}` or `px={0.5}`

2023-03-29 04:44 UTC, dhruvkelawala commented on packages/extension/src/shared/wallet.model.ts
>  export type UpdateMultisigThresholdPayload = {
I don't understand why these types are inside `wallet.model.ts`? They shouldn't be here imo

2023-03-29 05:06 UTC, diegodelrieu commented on packages/extension/src/shared/wallet.model.ts
>  export type UpdateMultisigThresholdPayload = {
true good catch

2023-03-29 05:07 UTC, diegodelrieu commented on packages/extension/src/shared/call/changeMultisigSignersCall.ts
> +      validateAndParseAddress(call.contractAddress)
I saw this in the 2fa calls files, I'm indifferent about either but I think we should only have one way of checking this

2023-03-30 13:53 UTC, simonheys approved these changes

2023-03-31 06:35 UTC, dhruvkelawala approved these changes

2023-03-31 09:52 UTC, merged