(WIP) feat: account names
argentlabs/argent-x pull request #284
Opened 2022-02-12 15:11 UTC by jgresham

Implements #263 
Needs cleanup once overall UI flow and functionality is approved.

https://user-images.githubusercontent.com/3721291/153716801-0204fcca-82fc-476d-944a-df65397bfc77.mp4

https://user-images.githubusercontent.com/3721291/153716798-e24eb527-78ca-49af-9ded-7eb830b58889.mp4

2022-02-14 10:30 UTC, delaaxe commented
Thanks for you contribution John, this is great! Small nitpick: it seems that when toggling edit mode, everything that's below the name shifts vertically by 1px. Possible to keep it all fixed?

Also, let me know when you think it's ready so I can review the code.

2022-02-19 02:14 UTC, jgresham commented
@delaaxe fixed the 1px UI shifting bug and cleaned up the PR.
Some things to consider:

1. EditableHeader isn't fully tested and may have repeat css from another component
2. account.ts might need some organization
3. in general, jsdoc strings would be helpful
4. wallet/account naming seems mixed #311 

note: this is separate from starknet's cli `--account=my_account`

2022-02-21 10:38 UTC, delaaxe requested changes

2022-02-21 10:38 UTC, delaaxe commented on packages/extension/src/ui/screens/ConfirmScreen.tsx
>      accountNumber: number
shouldn't be needed anymore

2022-02-21 10:38 UTC, delaaxe commented on packages/extension/src/ui/states/account.ts
> +const calcAccountNumber = (
please avoid abbreviations and acronyms as much as possible

2022-02-21 10:38 UTC, delaaxe commented on packages/extension/src/ui/states/account.ts
> +}
i think this should be more along the lines of:

```python
index = 1
while getDefaultAccountName(index) not in accountNames:
  index++
return getDefaultAccountName(index)
```

2022-02-21 10:38 UTC, delaaxe commented on packages/extension/src/ui/utils/wallets.ts
> +  accountName: string | undefined,
```suggestion
  accountName?: string,
```

2022-02-21 10:38 UTC, delaaxe commented on packages/extension/src/ui/utils/recovery.ts
> +    setAccountNamesFromBackup(wallets)
this function wouldn't be needed if there was a single source of truth for account names

2022-02-21 10:38 UTC, delaaxe commented on packages/extension/src/ui/Wallet.ts
> +  name?: string
this field shouldn't exist on this class

2022-02-23 00:59 UTC, jgresham commented on packages/extension/src/ui/states/account.ts
> +  persist(
I think it could be cleaner and easier to reason about where the data is coming from. I kept in account store because I thought it would be less changes elsewhere. Few thoughts:

Pros for separate stores:
1. Keep the data coming from `recovery.ts recover()` (account store before these changes) separate from any user input/metadata
2. More future proof if there are plans for user's to add more account details.

Cons for separate stores:
1. UI components would need to use multiple stores to show all the data for an account

2022-02-23 01:03 UTC, jgresham commented on packages/extension/src/ui/states/account.ts
> +}
I don't think this would work with the structure of `accountNames` being:
https://github.com/argentlabs/argent-x/pull/284/files#diff-7b1dbae5fd43e7fa9c15da5204f37abd705b208adc0be83178e26bcd3816c32dR48-R54
```
accountNames: {
              ...state.accountNames,
              [networkId]: {
                ...state.accountNames[networkId],
                [address]: name,
              },
            },
```

2022-02-23 01:04 UTC, jgresham commented on packages/extension/src/ui/utils/recovery.ts
> +    setAccountNamesFromBackup(wallets)
correct, but would need to add an additional "useStore" to UI components.

2022-02-23 01:14 UTC, jgresham commented on packages/extension/src/ui/Wallet.ts
> +  name?: string
I'm not aware how `Wallet`  and `Account` is used with starknet. Is this class better named `Account`?

2022-02-23 13:40 UTC, delaaxe commented
@jgresham I've made the changes. Do you see anything that could be wrong or that I might've missed before I merge? Thanks again for your help

2022-02-23 16:58 UTC, jgresham commented on packages/extension/src/ui/states/accountMetadata.ts
> +  while (names.includes(`Account ${index}`)) {
I think this method of determining the default account name has a bug. On first open of my wallet, all accounts had "Account 1" as the name. Also, my opinion is that the n-th account should be named Account n, regardless of the other account names.
![account-numbers](https://user-images.githubusercontent.com/3721291/155368097-3b9d2fb7-5270-4601-8097-908b92dd1f50.png)

2022-02-23 17:07 UTC, jgresham commented on packages/extension/src/ui/states/accountMetadata.ts
> +  while (names.includes(`Account ${index}`)) {
Account names may need to be set to the default name (if not set) after `recovery` to fix this.

2022-02-23 17:13 UTC, jgresham commented on packages/extension/src/ui/states/accountMetadata.ts
> +      const name = getDefaultAccountName(account)
`names` may need to be passed in here as the state isn't updated for each iteration in `getDefaultAccountName`

2022-02-23 17:31 UTC, delaaxe commented
@jgresham just reverted it to the way you did it before. seeing any more issues?

2022-02-23 18:03 UTC, jgresham commented
> @jgresham just reverted it to the way you did it before. seeing any more issues?

I don't see any new commits?

2022-02-23 21:32 UTC, delaaxe commented
> > @jgresham just reverted it to the way you did it before. seeing any more issues?
> 
> I don't see any new commits?

sorry I pushed to wrong branch. should be ok now

2022-02-24 02:11 UTC, jgresham commented
@delaaxe just tested it out. looks good to me!

2022-02-24 08:16 UTC, delaaxe approved these changes

2022-02-24 08:17 UTC, merged