fix(dapp): unhandled error when adding token in Dapp
argentlabs/argent-x pull request #345
Opened 2022-02-26 03:00 UTC by jasonzhouu

2022-02-28 13:53 UTC, delaaxe requested changes

2022-02-28 13:53 UTC, delaaxe commented on packages/dapp/src/components/TokenDapp.tsx
> +  const [errorMessageOfAddERC20Token, setErrorMessageOfAddERC20Token] =
```suggestion
  const [addTokenError, setAddTokenError] =
```

2022-02-28 13:53 UTC, delaaxe commented on packages/dapp/src/components/TokenDapp.tsx
> +  const [errorMessageOfAddETHToken, setErrorMessageOfAddETHToken] = useState("")
One error message variable should be enough

2022-02-28 13:53 UTC, delaaxe commented on packages/dapp/src/components/TokenDapp.tsx
> +          }}
Please prefer async/await notation

2022-02-28 13:53 UTC, delaaxe commented on packages/dapp/src/components/TokenDapp.tsx
> +                })
Please prefer async/await notation

2022-02-28 14:10 UTC, jasonzhouu commented on packages/dapp/src/components/TokenDapp.tsx
> +  const [errorMessageOfAddETHToken, setErrorMessageOfAddETHToken] = useState("")
If only one variable is used, an error occurs when adding the erc20 token, the error message will be displayed in both places

2022-02-28 14:11 UTC, jasonzhouu commented on packages/dapp/src/components/TokenDapp.tsx
> +          }}
OK. updated

2022-02-28 14:11 UTC, jasonzhouu commented on packages/dapp/src/components/TokenDapp.tsx
> +                })
updated

2022-02-28 14:12 UTC, delaaxe commented on packages/dapp/src/components/TokenDapp.tsx
> +  const [errorMessageOfAddETHToken, setErrorMessageOfAddETHToken] = useState("")
It's fine displaying just one error in one place

2022-03-03 10:42 UTC, delaaxe approved these changes

2022-03-03 10:42 UTC, merged

2022-03-03 10:42 UTC, jasonzhouu commented
Thank you