refactor(ui): reuse ConfirmScreen in HideTokenScreen
argentlabs/argent-x pull request #346
Opened 2022-02-26 10:45 UTC by jasonzhouu

https://github.com/argentlabs/argent-x/issues/293

2022-02-28 13:58 UTC, delaaxe requested changes
This is much cleaner, thank you

2022-02-28 13:58 UTC, delaaxe commented on packages/extension/src/ui/screens/HideTokenScreen.tsx
> +  const handleSubmit = async () => {
Does this function need to be async?

2022-02-28 13:58 UTC, delaaxe commented on packages/extension/src/ui/screens/HideTokenScreen.tsx
> +    } catch (e) {
Hide error variable if unused
```suggestion
    } catch {
```

2022-02-28 14:14 UTC, jasonzhouu commented on packages/extension/src/ui/screens/HideTokenScreen.tsx
> +  const handleSubmit = async () => {
Thank you for your review. 
Updated

2022-03-03 10:43 UTC, delaaxe approved these changes

2022-03-03 10:43 UTC, merged