feature: disconnect from dapp
argentlabs/argent-x pull request #348
Opened 2022-02-26 15:51 UTC by jasonzhouu

Implements  https://github.com/argentlabs/argent-x/issues/262

https://user-images.githubusercontent.com/19926174/155849631-67924e4e-4618-4153-a907-f38f0981a87d.mov

https://user-images.githubusercontent.com/19926174/155849796-7e4bf8e1-819d-4914-a357-95b0a5d66652.mov

## PS
npm package `@argent/get-starknet` should be upgraded in the Dapp.

2022-02-28 14:04 UTC, delaaxe requested changes

2022-02-28 14:04 UTC, delaaxe commented on packages/extension/src/background/index.ts
> +        console.log("host", host)
console.logs

2022-02-28 14:04 UTC, delaaxe commented on packages/extension/src/shared/MessageType.ts
> +  | { type: "DISCONNECT_RES" }
The order should stay:
EVENT
EVENT_RES
EVENT2
EVENT2_RES

2022-02-28 14:04 UTC, delaaxe commented on packages/get-starknet/src/index.ts
> +  disconnect: async () => {},
Should be like others:

```suggestion
  disconnect: fail,
```

2022-02-28 14:44 UTC, jasonzhouu commented
> See the comment I made on the issue

You mean implement 'chainChanged', 'connect', 'disconnect'?

2022-02-28 14:45 UTC, jasonzhouu commented
It seems that Metamask don't emit 'disconnect' event when use disconnect dapp from Metamask.

2022-02-28 14:46 UTC, jasonzhouu commented
Metamask's 'disconnect' event is emitted when RPC is disconnected:

> In general, this will only happen due to network connectivity issues or some unforeseen error.

https://docs.metamask.io/guide/ethereum-provider.html#disconnect

2022-02-28 17:12 UTC, jasonzhouu commented
It seems that the request type of the develop branch is a bit different, I'll check it out tomorrow

2022-02-28 17:17 UTC, jasonzhouu commented
> i was referencing this comment: [#262 (comment)](https://github.com/argentlabs/argent-x/issues/262#issuecomment-1054294025)

This PR does not act like JediSwap. It seems that action of disconnection in JediSwap does not interact with ArgentX.

2022-02-28 17:21 UTC, delaaxe commented
Yes. Disconnecting should not remove from whitelist

2022-03-03 10:46 UTC, jasonzhouu commented
Does argentx needs to record when user disconnect dapp from argentx, like what Metamask did?

2022-03-09 10:16 UTC, gergold commented
This should be covered by #378 
So closing this PR

2022-03-09 10:16 UTC, closed without merging