feat: store tokens in background
argentlabs/argent-x pull request #582
Opened 2022-05-05 14:29 UTC by janek26

this allows to do checks on the token list without opening the UI
eg: checking if a token already exists in case a dapp wants to add one

2022-05-05 15:21 UTC, delaaxe requested changes

2022-05-05 15:21 UTC, delaaxe commented on packages/extension/src/shared/token.ts
> +  Omit<Token, "image" | "showAlways" | "address">
define a base interface which has the minimum number of fields and make `Token` extend that interface. no `Omit` here

2022-05-05 15:21 UTC, delaaxe commented on packages/extension/src/shared/token.ts
> +  b: Pick<Token, "address" | "networkId">,
similarly, this is hacky

2022-05-05 15:21 UTC, delaaxe commented on packages/extension/src/ui/states/tokens.ts
> +import { number } from "starknet"
at some point we should change the pattern to just 
```typescript
import starknet from "starknet"
```
and use methods form there instead of importing very generic sounding names like `number`

2022-05-05 15:21 UTC, delaaxe commented on packages/extension/src/ui/states/tokens.ts
> +    Partial<Omit<Token, "decimals" | "address" | "networkId">> {
see comment above

2022-05-05 15:21 UTC, delaaxe commented on packages/extension/src/ui/states/tokens.ts
> +      tokens: state.tokens.filter((t) => t.address !== tokenAddress),
avoid single letter variables

2022-05-05 15:21 UTC, delaaxe commented on packages/extension/src/ui/states/tokens.ts
> +  const { data: tokens = [] } = useSWRImmutable("tokens", () => getTokens(), {
if `getTokens` doesn't use the `this` keyword, this is better written as

```suggestion
  const { data: tokens = [] } = useSWRImmutable("tokens", getTokens, {
```

2022-05-05 15:21 UTC, delaaxe commented on packages/extension/src/ui/states/tokens.ts
> +export const removeToken = (tokenAddress: TokenDetails["address"]) => {
can't just use `tokenAddress: string`?

2022-05-05 15:21 UTC, delaaxe commented on packages/extension/src/ui/utils/messaging.ts
> +//   | { type: "ADD_TOKEN_RES"; data: boolean }
commented code

2022-05-05 15:30 UTC, janek26 commented on packages/extension/src/background/tokens.ts
> +  }
yes sorry, evolved into this monster :D

2022-05-05 15:36 UTC, janek26 commented on packages/extension/src/ui/states/tokens.ts
> +import { number } from "starknet"
the name of that export is being worked on in the starknet.js group currently

2022-05-05 15:38 UTC, janek26 commented on packages/extension/src/ui/states/tokens.ts
> +export const removeToken = (tokenAddress: TokenDetails["address"]) => {
it's equivallent. With the benefit that this type will change when the interface changes :) helps to catch errors while refactors imo

2022-05-05 15:51 UTC, delaaxe commented on packages/extension/src/ui/states/tokens.ts
> +export const removeToken = (tokenAddress: TokenDetails["address"]) => {
I doubt the address type will change, and even if it does there will be plenty of compile errors everywhere. `string` is more readable and easier to understand

2022-05-05 15:59 UTC, janek26 commented on packages/extension/src/ui/states/tokens.ts
> +export const removeToken = (tokenAddress: TokenDetails["address"]) => {
done :)

2022-05-06 08:34 UTC, janek26 commented on packages/extension/src/shared/token.ts
> +  b: Pick<Token, "address" | "networkId">,
It ensures you need to pass as little data as possible, I think that's a good pattern. 
It allows you to compare Tokens with BigInt decimals with Tokens with number decimals ie

2022-05-06 08:41 UTC, delaaxe approved these changes

2022-05-06 08:41 UTC, merged