feat: add `addChain` method for dapps
argentlabs/argent-x pull request #639
Opened 2022-05-18 16:14 UTC by dhruvkelawala

closes #623

2022-05-18 18:11 UTC, delaaxe reviewed
good job

2022-05-18 18:11 UTC, delaaxe commented on packages/extension/src/inpage.ts
> +
Now that this `StarknetWindowObject.request` method is becoming pretty fat, can we factor out 2 functions, one for each of the `wallet_watchAsset` & `wallet_addStarknetChain` cases?

2022-05-18 18:11 UTC, delaaxe commented on packages/extension/src/ui/features/actions/ActionScreen.tsx
> +      // action.payload
commented code

2022-05-18 18:11 UTC, delaaxe commented on packages/extension/src/ui/features/actions/AddNetworkScreen.tsx
> +  //   }
commented code

2022-05-18 18:11 UTC, delaaxe commented on packages/extension/src/ui/features/actions/AddNetworkScreen.tsx
> +          onSubmit={(e: React.FormEvent) => {
type is inferred here

```suggestion
          onSubmit={(e) => {
```

2022-05-18 18:11 UTC, delaaxe commented on packages/extension/src/ui/features/actions/AddNetworkScreen.tsx
> +                  "🚀 ~ file: AddNetworkScreen.tsx ~ line 139 ~ networks",
is there a tool that generates this?

2022-05-18 18:11 UTC, delaaxe commented on packages/extension/src/ui/features/actions/AddNetworkScreen.tsx
> +              } catch (e) {
```suggestion
              } catch {
```

2022-05-18 18:22 UTC, dhruvkelawala commented on packages/extension/src/inpage.ts
> +
@janek26 and I had a call yesterday and felt that many files need refactoring. Should we refactor this function along with that or should I do it in this PR?

2022-05-18 18:26 UTC, delaaxe commented on packages/extension/src/inpage.ts
> +
it's ok to do some refactoring in feature PRs to keep things easy to understand, but yes bigger refactors should be in their own PRs

2022-05-19 07:22 UTC, delaaxe requested changes
much better now, just make sure `yarn build` still passes

2022-05-19 08:16 UTC, dhruvkelawala commented
@delaaxe This should fix build

2022-05-19 08:27 UTC, merged