Add account menu with following features
argentlabs/argent-x pull request #686
Opened 2022-05-30 08:01 UTC by dhruvkelawala

- View on Voyager
- Edit Account Name
- Export private key

2022-05-30 09:08 UTC, delaaxe requested changes
should the icons be aligned?
<img width="289" alt="image" src="https://user-images.githubusercontent.com/1091900/170958275-f0fc8b9c-f938-4ca4-b952-b532785890ea.png">

2022-05-30 09:08 UTC, delaaxe commented on packages/extension/src/shared/MessageType.ts
> +    }
```suggestion
  | { type: "EXPORT_PRIVATE_KEY" }
```

2022-05-30 09:08 UTC, delaaxe commented on packages/extension/src/ui/features/accountTokens/AccountMenu.tsx
> +  const [isMenuOpen, setMenuOpen] = useState<boolean>(false)
```suggestion
  const [isMenuOpen, setMenuOpen] = useState(false)
```

2022-05-30 09:08 UTC, delaaxe commented on packages/extension/src/ui/features/exportPrivateKey/index.tsx
> +import { FC, ReactNode } from "react"
don't create a folder with one file, this can go in the accountTokens feature since it's where it's used

2022-05-30 09:08 UTC, delaaxe commented on packages/extension/src/ui/hooks/useOnClickOutside.ts
> +  handler: undefined | (() => void),
```suggestion
  handler?: () => void,
```

2022-05-30 09:08 UTC, delaaxe commented on packages/extension/src/ui/hooks/useOnClickOutside.ts
> +import { RefObject, useEffect, useRef } from "react"
don't create a `hooks` folder, put this file close to where it's used, otherwise in `services` folder

2022-05-30 09:08 UTC, delaaxe commented on packages/extension/src/ui/services/voyager.service.ts
> +  window.open(network.explorerUrl, "_blank")?.focus()
this should open the account page on voyager, not the home page

2022-05-30 09:15 UTC, dhruvkelawala commented on packages/extension/src/background/wallet.ts
> +
I am not sure.

2022-05-30 09:54 UTC, delaaxe requested changes

2022-05-30 09:54 UTC, delaaxe commented on packages/extension/src/ui/features/accountTokens/AccountMenu.tsx
> +import { useCurrentNetwork } from "../networks/useNetworks"
warnings
<img width="671" alt="image" src="https://user-images.githubusercontent.com/1091900/170965704-1f438fcf-db23-4501-bd28-3367f15b977a.png">

2022-05-30 09:54 UTC, delaaxe commented on packages/extension/src/ui/features/accountTokens/exportPrivateKey.tsx
> +import { FC, ReactNode } from "react"
file should be named `ExportPrivateKeyScreen`

2022-05-30 09:54 UTC, delaaxe commented on packages/extension/src/ui/services/useOnClickOutside.ts
> +  node: RefObject<T | undefined>,
don't use generics when not needed

```suggestion
export default function useOnClickOutside(
  node: RefObject<HTMLElement | undefined>,
```

2022-05-30 09:54 UTC, delaaxe commented on packages/extension/src/ui/services/voyager.service.ts
> +    window.open(network.explorerUrl, "_blank")?.focus()
in which situation do we want to show the goerli homepage to the user? i don't think this is needed

2022-05-30 09:54 UTC, delaaxe commented on packages/extension/src/ui/services/useOnClickOutside.ts
> +export default function useOnClickOutside<T extends HTMLElement>(
don't use `export default` unless there's no other way
```suggestion
export function useOnClickOutside<T extends HTMLElement>(
```

2022-05-30 09:58 UTC, dhruvkelawala commented on packages/extension/src/ui/services/voyager.service.ts
> +    window.open(network.explorerUrl, "_blank")?.focus()
In no situation, it's just a placeholder when address is not available because `useSelectedAccount` gives `Account | undefined`. I don't think we should worry about this.

2022-05-30 10:02 UTC, delaaxe commented on packages/extension/src/ui/services/voyager.service.ts
> +export const openVoyager = (network: Network, address?: string) => {
this is not correct. if there is no address this function shouldn't be called
```suggestion
export const openVoyagerAddress = (network: Network, address: string) => {
```

2022-05-30 10:03 UTC, dhruvkelawala commented on packages/extension/src/ui/services/useOnClickOutside.ts
> +  node: RefObject<T | undefined>,
I think here generics are required so that we can use any HTMLElement, such as HTMLDivElement that we are using. This is a reusable hook, therefore generics are required.

Also,
<img width="1289" alt="Screenshot 2022-05-30 at 3 31 39 PM" src="https://user-images.githubusercontent.com/50968441/170969181-692d1a1d-d19a-43a5-a55e-b46104cd1a06.png">

2022-05-30 10:06 UTC, delaaxe commented on packages/extension/src/ui/services/useOnClickOutside.ts
> +  node: RefObject<T | undefined>,
they are not required, you need to change the `useOnClickOutside<HTMLElement>` to `useOnClickOutside` like I suggested

2022-05-30 10:19 UTC, delaaxe requested changes

2022-05-30 10:19 UTC, delaaxe commented on packages/extension/src/background/wallet.ts
> +
looks like nile private keys are strings: https://github.com/OpenZeppelin/nile#setup

as @janek26 suggested, we should be as compatible as possible with nile

2022-05-30 10:19 UTC, delaaxe commented on packages/extension/src/ui/services/voyager.service.ts
> +export const openVoyager = (network: Network, address?: string) => {
this remains

2022-05-30 10:36 UTC, delaaxe commented on packages/extension/src/ui/features/accountTokens/ExportPrivateKeyScreen.tsx
> +        <H2>Export Private Key</H2>
```suggestion
        <H2>Export private key</H2>
```

2022-05-31 08:29 UTC, delaaxe commented on packages/extension/src/ui/features/accountTokens/AccountMenu.tsx
> +              <WarningIcon /> Export Private Key
```suggestion
              <EditIcon /> Edit name
            </MenuItem>
          </MenuItemWrapper>
          <Separator />
          <MenuItemWrapper onClick={() => navigate(routes.exportPrivateKey())}>
            <MenuItem>
              <WarningIcon /> Export private key
```

2022-05-31 10:34 UTC, delaaxe requested changes
great, please clean the warnings in background and resolve the merge conflicts and we're good

2022-05-31 10:34 UTC, delaaxe commented on packages/extension/src/ui/features/accountTokens/usePrivateKey.ts
> +  const [privateKey, setPrivateKey] = useState<string | undefined>(undefined)
```suggestion
  const [privateKey, setPrivateKey] = useState<string>()
```

2022-05-31 10:34 UTC, delaaxe commented on packages/extension/src/ui/features/accountTokens/usePrivateKey.ts
> +    async () => await getPrivateKey(),
```suggestion
    getPrivateKey,
```

2022-05-31 10:34 UTC, delaaxe commented on packages/extension/src/ui/features/accountTokens/usePrivateKey.ts
> +    getPrivateKeyCallback().then((pk) => setPrivateKey(pk))
```suggestion
    getPrivateKeyCallback().then(setPrivateKey)
```

2022-05-31 11:20 UTC, delaaxe approved these changes

2022-05-31 11:20 UTC, merged