feat(background): use constructor-initialized proxy
argentlabs/argent-x pull request #690
Opened 2022-05-30 13:30 UTC by delaaxe

2022-05-31 09:46 UTC, delaaxe commented
to be merged with cairo 0.9 support

2022-06-01 10:11 UTC, janek26 commented
This should differentiate between Mainnet and Testnet, as we still need the old version on main net until 0.9.0 releases on mainnet

2022-06-01 11:41 UTC, janek26 requested changes
This should differentiate between Mainnet and Testnet, as we still need the old version on main net until 0.9.0 releases on mainnet

2022-06-01 14:40 UTC, delaaxe commented on packages/extension/src/background/wallet.ts
> +    if (networkId === "mainnet-alpha") {
TS2367: This condition will always return 'true' since the types '"goerli-alpha"' and '"integration"' have no overlap.

2022-06-02 17:45 UTC, janek26 commented
please keep using the old compiled contract versions for the old deployment flow

2022-06-02 17:45 UTC, janek26 commented
please keep using the old compiled contract versions for the old deployment flow

2022-06-03 07:37 UTC, delaaxe commented on packages/extension/src/ui/features/settings/NetworkSettingsFormScreen.tsx
>    }, [props])
@janek26 `props` is a different reference on every render so `useMemo` effectively does nothing here and potentially consumes a bunch of extra memory, am I wrong?

2022-06-03 09:24 UTC, janek26 commented on packages/extension/src/ui/features/settings/NetworkSettingsFormScreen.tsx
>    }, [props])
right, should be 
```suggestion
  }, [props.network, props.mode])
```

2022-06-03 18:44 UTC, janek26 approved these changes

2022-06-03 18:44 UTC, merged