support Ledger Nano S/SP/X devices (blind signing)
argentlabs/argent-x pull request #694
Opened 2022-05-31 13:53 UTC by yogh333

2022-06-01 09:22 UTC, janek26 commented
![Bildschirmfoto 2022-06-01 um 11 21 58](https://user-images.githubusercontent.com/6831124/171371845-1524521f-9b35-4bcc-9031-38a0c1dfee8e.png)

Hey, I don't think this has the chance to work this way, as you can see in the error. The background process has no access to the window object and usb methods.
It would need to be it's own content script.

2022-06-01 11:42 UTC, janek26 requested changes
most likely this won't get merged until we support multiple account types

2022-06-02 05:58 UTC, yogh333 commented
Regarding the error it is due to the fact that the first time you add a device you have to launch the extension in a chrome tab (see Expand in settings menu). But you say that there is another solution ?

2022-06-02 10:05 UTC, delaaxe commented
given the sensitive nature of a wallet's code base, I'd rather not add a dependency coming from someone's personal github account

2022-06-02 13:51 UTC, janek26 commented
@yogh333 maybe you can get that under the ledger org?

2022-06-06 08:45 UTC, yogh333 commented
@janek26 I am working for Ledger with my personal github account. I assume that there are several PRs coming from other github personal accounts so what is the concern here ? Code is open source, can be reviewed, commented, improved, modified etc...

2022-06-06 08:47 UTC, yogh333 commented
@janek26 [Regarding this issue](https://github.com/argentlabs/argent-x/pull/694#issuecomment-1143352608), did you try by first trying to open the extension in a tab before trying to connect to a Ledger device ?

2022-06-06 10:00 UTC, yogh333 commented on packages/extension/package.json
> +    "@yogh/starknetjs-signer-ledger": "^1.1.1",
Ok this is an implementation of Starknet JS Signer interface for Ledger device. You mean that you would be more confient if this package come from [LedgerHQ](https://github.com/LedgerHQ) ?

2022-06-06 10:04 UTC, delaaxe commented on packages/extension/package.json
> +    "@yogh/starknetjs-signer-ledger": "^1.1.1",
Yes exactly

2022-06-06 13:33 UTC, yogh333 commented on packages/extension/package.json
> +    "@yogh/starknetjs-signer-ledger": "^1.1.1",
Done ;)

2022-06-08 16:39 UTC, yogh333 commented
Hello, 
What is the status for the merge ? If there is anything blocking, please tell me so I can help...

2022-11-18 08:59 UTC, closed without merging