(feat): Hide accounts
argentlabs/argent-x pull request #699
Opened 2022-06-02 09:02 UTC by dhruvkelawala

2022-06-02 09:16 UTC, delaaxe reviewed
is there a figma for this? why is the UX different than for hiding localhost accounts?

2022-06-02 09:16 UTC, delaaxe commented on packages/extension/src/ui/features/accountTokens/AccountMenu.tsx
> +                  <VisibilityOff fontSize={"inherit"} htmlColor={"white"} />
```suggestion
                  <VisibilityOff fontSize="inherit" htmlColor="white" />
```

2022-06-02 09:16 UTC, delaaxe commented on packages/extension/src/ui/features/accountTokens/useHideAccountCallback.tsx
> +  return useCallback(async (account: Account) => {
is useCallback really needed? honest question

2022-06-02 09:16 UTC, delaaxe commented on packages/extension/src/ui/features/accounts/accounts.state.ts
> +  accounts: { [address: string]: Account }
```suggestion
  accounts: Record<string, Account>
```

2022-06-02 09:26 UTC, dhruvkelawala commented on packages/extension/src/ui/features/accounts/accounts.state.ts
> +  accounts: { [address: string]: Account }
Cannot use spread operator on `Record<string, Account>` and we are using spread operator in `hideAccount`

2022-06-02 09:52 UTC, delaaxe reviewed
great. one last question: after restarting the browser, the hidden accounts reappear. is this expected?

2022-06-02 09:58 UTC, dhruvkelawala commented
No it isn't expected and it isn't happening on my end. But we are updating logic anyways where we won't remove the Account from the storage but just add it to the list of HiddenAccounts as discussed with @juniset

2022-06-02 13:52 UTC, janek26 commented
as far as I understood this is not ready for review yet. Correct me if I'm wrong

2022-06-03 09:22 UTC, janek26 reviewed
after latest merges there are also conflicts

2022-06-03 09:22 UTC, janek26 commented on packages/extension/src/background/accountMessaging.ts
> +        data: (await wallet.getAccounts()).filter((acc) => !acc.hidden),
I think getAccounts default behavior should be to only show non hidden accounts.
+ there should be an optional argument to show hidden accounts if you want to:
```
function getAccounts(showHidden = false): Accounts[]
```

2022-06-03 09:22 UTC, janek26 commented on packages/extension/src/background/accountMessaging.ts
> +        console.log("Account Hide Successful")
remove console log before going to prod

2022-06-03 09:23 UTC, janek26 commented
please rebase/merge develop

2022-06-03 09:24 UTC, dhruvkelawala commented on packages/extension/src/background/accountMessaging.ts
> +        data: (await wallet.getAccounts()).filter((acc) => !acc.hidden),
I also had the similar idea, but on most of the places where we are using getAccounts(), we want all the accounts including the hidden ones. That's why I thought it was a better idea to filter them here.

2022-06-03 09:27 UTC, delaaxe requested changes

2022-06-03 09:27 UTC, delaaxe commented on packages/extension/src/background/wallet.ts
> +      hidden: false,
idem

2022-06-03 09:27 UTC, delaaxe commented on packages/extension/src/ui/features/accounts/accounts.state.ts
> +    })),
why are changes needed in UI state if everything is handled in background? @janek26

2022-06-03 09:27 UTC, delaaxe commented on packages/extension/src/ui/services/messaging.ts
> +  } catch (error) {
```suggestion
  } catch {
```

2022-06-03 09:27 UTC, delaaxe commented on packages/extension/src/background/wallet.ts
> +              hidden: false,
should not be if `hidden` is `boolean | undefined`

```suggestion
```

2022-06-03 10:05 UTC, dhruvkelawala commented on packages/extension/src/ui/features/accounts/accounts.state.ts
> +    })),
Because AccountList is fetched from the UI state, not the background. Accounts are fetched from the background only once after the extension is reloaded or browser is restarted

2022-06-03 10:50 UTC, delaaxe commented on packages/extension/src/background/accountMessaging.ts
> +        data: (await wallet.getAccounts()).filter((acc) => !acc.hidden),
I agree with Janek, his suggestion seems cleaner

2022-06-03 19:09 UTC, delaaxe approved these changes

2022-06-03 19:38 UTC, janek26 commented
Hey, after rebasing this PR I think we should change several things:
1. Don't have multiple source of truth, the background should hold the only state that determines if an account is hidden or not. Please remove `hiddenAccounts` from https://github.com/argentlabs/argent-x/blob/feat/hide-accounts/packages/extension/src/ui/features/accounts/accounts.state.ts#L24
2. getAccounts should default to not returning hidden accounts. That way the UI will fully ignore them.
3. useAccounts accounts object can be kept in sync with background messages like you can find here: https://github.com/argentlabs/argent-x/blob/86849c6a07d1ed7ff46121a97539b6e139db81a7/packages/extension/src/ui/features/accountTokens/tokens.state.ts

I know it's done differently with `addAccount` on the same state object, but long term that should move into a similar pattern

2022-06-03 19:52 UTC, delaaxe commented
1. I had the exact same thought on multiple sources of truth but forgot to mention it
2. Keep in mind knowing hidden accounts may be needed to determine if MigrationDisclaimerScreen needs to be show

2022-06-04 07:36 UTC, delaaxe requested changes
1. I had the exact same thought on multiple sources of truth but forgot to mention it
2. Keep in mind knowing hidden accounts may be needed to determine if MigrationDisclaimerScreen needs to be show

2022-06-06 07:42 UTC, dhruvkelawala commented
Not ready for merge. Needs testing. 

Bug 1: Adding a new account and reloading extension, unhides and shows all the hidden account. Not everytime, sometimes only.

Bug 2: Sometimes adding a new account, recovers the old hidden account instead of creating a new account.

2022-06-06 07:58 UTC, delaaxe requested changes

2022-06-06 07:58 UTC, delaaxe commented on packages/extension/src/background/accountMessaging.ts
> +      } catch (error) {
Unused variable

2022-06-06 07:58 UTC, delaaxe commented on packages/extension/src/background/wallet.ts
> +  public async getAccounts(showHidden = false): Promise<WalletAccount[]> {
Shouldn't the default be true?

This is not a display method, so "show" isn't the right term. "includeHidden" more appropriate

2022-06-06 07:58 UTC, delaaxe commented on packages/extension/src/ui/features/accountTokens/AccountMenu.tsx
> +    navigate(routes.accounts())
Can you try navigate(await recover({ showList: true })? Should fix some of the bugs

2022-06-06 07:58 UTC, delaaxe commented on packages/extension/src/ui/features/accounts/accounts.state.ts
> +}
All this may be unnecessary if you use the recover method from above

2022-06-06 07:58 UTC, delaaxe commented on packages/extension/src/ui/services/backgroundAccounts.ts
> +}
Remove the try/catch, it's redundant because already throwing in REJ case

2022-06-06 08:17 UTC, dhruvkelawala commented on packages/extension/src/background/wallet.ts
> +  public async getAccounts(showHidden = false): Promise<WalletAccount[]> {
See the suggestion by Janek 

https://github.com/argentlabs/argent-x/pull/699#discussion_r888777127

2022-06-06 08:20 UTC, dhruvkelawala commented on packages/extension/src/ui/features/accounts/accounts.state.ts
> +}
I used @janek26's suggestion of keeping the state account in sync with background using messaging

2022-06-06 09:44 UTC, delaaxe commented on packages/extension/src/ui/features/accounts/accounts.state.ts
> +}
Is this still needed after the recover change?

2022-06-06 09:45 UTC, delaaxe commented on packages/extension/src/background/wallet.ts
> +  public async getAccounts(showHidden = false): Promise<WalletAccount[]> {
Naming unresolved

2022-06-09 08:55 UTC, dhruvkelawala commented on packages/extension/src/ui/features/accounts/accounts.state.ts
> +}
Removed

2022-06-09 08:55 UTC, dhruvkelawala commented on packages/extension/src/ui/features/accountTokens/AccountMenu.tsx
> +    navigate(routes.accounts())
Done

2022-06-09 08:55 UTC, dhruvkelawala commented on packages/extension/src/background/wallet.ts
> +  public async getAccounts(showHidden = false): Promise<WalletAccount[]> {
Done

2022-06-13 08:34 UTC, delaaxe commented
we should deactivate the delete account now that we can hide: https://github.com/argentlabs/argent-x/blob/develop/packages/extension/src/ui/features/accounts/AccountListScreen.tsx#L119

2022-06-13 08:59 UTC, delaaxe commented
julien recommended removing it altogether for deprecated accounts and moving it to account menu for localhost accounts (because could be easily clicked by mistake as is) but up to you depending on the load

2022-06-13 10:28 UTC, janek26 commented
makes sense, but probably not as part of this PR

2022-06-14 07:27 UTC, janek26 commented
we agreed to
1. move "delete account" from account list into the account menu
2. always just show one of "delete account" or "hide account", depending on if an account is deprecated or on localhost.
3. always show a confirm screen in front of "delete account" and "hide account" action

2022-06-14 20:37 UTC, janek26 approved these changes

2022-06-14 21:15 UTC, delaaxe approved these changes

2022-06-14 21:16 UTC, merged