feat: add notification badge
argentlabs/argent-x pull request #931
Opened 2022-07-12 11:59 UTC by dhruvkelawala

<img width="82" alt="Screenshot 2022-07-12 at 12 59 39 PM" src="https://user-images.githubusercontent.com/50968441/178485039-ae59e794-0163-49c7-974b-222a29376c76.png">

2022-07-12 12:34 UTC, janek26 requested changes

2022-07-12 12:34 UTC, janek26 commented on packages/extension/src/background/transactions/onchain.ts
> +  browserAction.setBadgeBackgroundColor({ color: "#29C5FF" })
please move this into the `TransactionUpdateListener` handler in https://github.com/argentlabs/argent-x/blob/develop/packages/extension/src/background/transactions/notifications.ts#L12

2022-07-12 12:34 UTC, janek26 commented on packages/extension/src/background/transactions/transactions.ts
> +    await handleUpdate()
if you move it this is not required

2022-07-12 14:47 UTC, dhruvkelawala commented on packages/extension/src/background/transactions/onchain.ts
> +  browserAction.setBadgeBackgroundColor({ color: "#29C5FF" })
Yep. I thought about it as well. However, I thought as we already had pending transactions available in the above file, I should do it there

2022-07-13 15:55 UTC, janek26 commented on packages/extension/src/background/transactions/notifications.ts
> +  if (IS_BROWSER) {
why is this needed? This won't run in the browser

2022-07-13 15:55 UTC, janek26 commented on packages/extension/src/background/transactions/notifications.ts
> +  newTransactions,
the first argument won't just be "new" transactions, but all transactions that updated compared to last time
so this should be `updatedTransactions`

2022-07-13 15:57 UTC, dhruvkelawala commented on packages/extension/src/background/transactions/notifications.ts
> +  if (IS_BROWSER) {
If we don't add it, it will fail during unit tests. IS_BROWSER just checks if typeof window is not undefined.

2022-07-13 18:20 UTC, dhruvkelawala commented on packages/extension/src/background/transactions/notifications.ts
> +    const pendingTransactions = [...newTransactions, ...allTransactions].filter(
It won't have "all" transactions. It will have allTransactions except the newTransactions because of this order https://github.com/argentlabs/argent-x/blob/e89ff58869afff78f3eaa7a1732995667684c2d7/packages/extension/src/background/transactions/transactions.ts#L101

Now, I know I can call txStore.getItems after adding new transaction and that way I would get all transactions including newTransactions. I just thought it would be better to keep them separate but I am open to change the order and allTransactions can include newTransaction as well.

2022-07-13 18:20 UTC, dhruvkelawala commented on packages/extension/src/background/transactions/notifications.ts
> +  newTransactions,
Cool

2022-07-14 11:50 UTC, dhruvkelawala commented
Closing this PR and rebasing this feature on #940

2022-07-14 11:50 UTC, closed without merging