Feature/new-storage-interface-for-tokens
argentlabs/argent-x pull request #932
Opened 2022-07-12 12:46 UTC by janek26

replace the token implementation from messaging system to the new storage class

2022-07-12 13:33 UTC, simonheys commented on packages/extension/test/setup.ts
> +}
Found out about this yesterday

```
/** mock global fetch() */
vi.stubGlobal("fetch", fetch)

/** satisfy checks to allow use of `import browser from "webextension-polyfill"` */
vi.stubGlobal("chrome", { runtime: { id: "testid" } })
```

2022-07-12 14:39 UTC, janek26 commented on packages/extension/test/setup.ts
> +}
very nice!

make sure to also let me know your thoughts on the new storage implementations, as they would be used everywhere some day it's important we're all aligned

2022-07-13 06:47 UTC, simonheys commented on packages/extension/src/shared/storage/__test__/hooks.test.tsx
> +})
Loving the tests! When running tests, all passing but this file shows a warning:

```
yarn test src/shared/storage/__test__/hooks.test.tsx
```

```
Warning: An update to Component inside a test was not wrapped in act(...).

When testing, code that causes React state updates should be wrapped into act(...):

act(() => {
  /* fire events that update state */
});
/* assert on the output */

This ensures that you're testing the behavior the user would see in the browser. Learn more at https://reactjs.org/link/wrap-tests-with-act
    at Component (/Applications/MAMP/htdocs/argent-x/packages/extension/src/shared/storage/__test__/hooks.test.tsx:100:42)
```

2022-07-13 06:51 UTC, simonheys commented on packages/extension/.eslintrc.js
> +    "react-hooks/exhaustive-deps": "off", // I dont see the reason for this check, I find myself always trying to use as few dependencies as possible, so it makes no sense to check if all are include
LOL I guess one other option here is to use `eslint-disable` to set it 'off' where explicitly intended with comments in the code? I would expect 'off' to be the exception rather than the norm?

2022-07-13 07:05 UTC, simonheys commented on packages/extension/src/ui/features/accountTokens/tokens.state.ts
> -
This is all still needed unfortunately, I can still see this empty error propagating into the UI

2022-07-13 07:12 UTC, simonheys commented
This is excellent work! Tests give great confidence that all works as intended.

One bonus thing that I would find very useful with something this fundamental is comments, maybe a short overview of the various storage types and simple examples of how they should be used? That could be work done as a separate story later though.

Once merged I would like to try using this for the dapp connections, I think that will help flush out any further comments.

There is one part where a fix should be reinstated, added a comment.

2022-07-13 07:13 UTC, simonheys requested changes
There is one part where a fix should be reinstated, added a comment.

2022-07-13 08:18 UTC, janek26 commented on packages/extension/.eslintrc.js
> +    "react-hooks/exhaustive-deps": "off", // I dont see the reason for this check, I find myself always trying to use as few dependencies as possible, so it makes no sense to check if all are include
okay we can do this aswell!

2022-07-13 10:43 UTC, janek26 commented on packages/extension/src/ui/features/accountTokens/tokens.state.ts
> -
I think I fixed the underlying issue now

2022-07-14 06:36 UTC, simonheys commented on packages/extension/src/ui/features/accountTokens/SendTokenScreen.tsx
> +  }, [maxClicked, maxFee, setMaxInputAmount, token?.address, token?.networkId]) // eslint-disable-line react-hooks/exhaustive-deps
Not a storage issue but is this issue fixed if `token` is memoized?

```
const token = useMemo(
  () => tokenDetails.find(({ address }) => address === tokenAddress),
  [tokenAddress, tokenDetails],
)
```

2022-07-14 06:38 UTC, simonheys commented on packages/extension/src/ui/features/accountTokens/TokenScreen.tsx
>    const token = tokenDetails.find(({ address }) => address === tokenAddress)
Same comment about possibly memoizing this

2022-07-14 06:48 UTC, simonheys commented on packages/extension/src/ui/features/actions/LoadingScreen.tsx
> +  useEffect(() => () => clearProgress(), []) // eslint-disable-line react-hooks/exhaustive-deps
Oof could fix this later but this one is because `useLoadingProgress` recreates `clearProgress` each time, probably needs converting to `useCallback` so its stable

2022-07-14 06:52 UTC, simonheys commented on packages/extension/src/ui/features/actions/transaction/useTransactionReview.ts
> +  }, [account, transactions]) // eslint-disable-line react-hooks/exhaustive-deps
Hm this doesn't seem right, I will make a note to come back and look at it. These comments are really useful!

2022-07-14 06:55 UTC, simonheys approved these changes
Few tiny notes, but looks good to go! Looking forward to giving this a try.

2022-07-14 09:46 UTC, janek26 commented on packages/extension/src/ui/features/actions/LoadingScreen.tsx
> +  useEffect(() => () => clearProgress(), []) // eslint-disable-line react-hooks/exhaustive-deps
I added a todo comment for this

2022-07-14 09:46 UTC, janek26 commented on packages/extension/src/ui/features/actions/transaction/useTransactionReview.ts
> +  }, [account, transactions]) // eslint-disable-line react-hooks/exhaustive-deps
Added another TODO comment for this

2022-07-14 09:55 UTC, merged