feat: add Sentry for Error Reporting
argentlabs/argent-x pull request #933
Opened 2022-07-12 15:56 UTC by dhruvkelawala

2022-07-12 15:57 UTC, dhruvkelawala commented
Basic Sentry added

2022-07-13 15:58 UTC, janek26 commented
Hey, I think the goal never was to add general sentry reporting, but to allow the user to report errors *explicitly* on the error screen. 
So next to "Reload" and "copy error" there would be a button "report error"

This is due to the confidential nature of a wallet. We dont want to collect any data without the user submitting it

2022-07-15 17:26 UTC, simonheys commented on packages/extension/src/ui/services/sentry.ts
> +      dsn: "https://c2c861914bb2448e873ea3235fe03e5e@o1315819.ingest.sentry.io/6567926",
IMO this should be a `process.env.SENTRY_DSN` or similar as it might need to differ between environments

2022-07-15 17:28 UTC, simonheys commented on packages/extension/src/ui/services/backgroundSettings.ts
> +    return data.key === key
Oof my bad for not doing this originally. Can the settings storage be migrated onto the new shared storage stack? If so we should add a jira ticket for it.

2022-07-15 17:29 UTC, simonheys commented on packages/extension/src/ui/components/ErrorBoundaryFallbackWithCopyError.tsx
> +  } = useBackgroundSettingsValue<ISettingsStorage["privacyErrorReporting"]>(
Not keen on the repetition of `privacyErrorReporting` here

2022-07-15 17:32 UTC, simonheys reviewed
Did you look into automated upload of the source maps to Sentry as part of this? Fairly essential. Could be a separate 'enhancement' ticket though, not sure how tricky it is to set up via github actions.

2022-07-15 17:36 UTC, simonheys commented on packages/extension/src/ui/components/ErrorBoundaryFallbackWithCopyError.tsx
> +  const reportToSentry = () => {
Won't make much difference here as the render is still impure but I'd like to see this as `useCallback(`

2022-07-15 19:18 UTC, janek26 commented on packages/extension/src/shared/settings.ts
> +export const isPrivacySettingsEnabled = true
should this be enabled?

2022-07-15 19:22 UTC, janek26 commented
if you think you could do automatic source map uploads to sentry that would be great!

2022-07-18 04:26 UTC, dhruvkelawala commented on packages/extension/src/shared/settings.ts
> +export const isPrivacySettingsEnabled = true
This has to be enabled for allowing user to change "Automatic Error Reporting" from settings > privacy

2022-07-18 04:27 UTC, dhruvkelawala commented on packages/extension/src/ui/services/backgroundSettings.ts
> +    return data.key === key
Yes :) . I spent more than 2hours just figuring out a weird issue as this was not present. I wasn't sure what was creating the problem xD

2022-07-18 04:28 UTC, dhruvkelawala commented on packages/extension/src/ui/components/ErrorBoundaryFallbackWithCopyError.tsx
> +  } = useBackgroundSettingsValue<ISettingsStorage["privacyErrorReporting"]>(
As in the variable name or the setting entirely?

2022-07-18 04:30 UTC, dhruvkelawala commented on packages/extension/src/ui/services/sentry.ts
> +        return integrations.filter(
I think this is better as it just removes the part from integrations that automatically captures exceptions.

2022-07-18 04:37 UTC, dhruvkelawala commented on packages/extension/src/ui/components/ErrorBoundaryFallbackWithCopyError.tsx
> +  const reportToSentry = () => {
I don't see much value in that, but will do it

2022-07-18 07:55 UTC, simonheys commented on packages/extension/src/ui/services/backgroundSettings.ts
> +    return data.key === key
Really sorry, I didn't know this could happen

2022-07-18 07:56 UTC, simonheys commented on packages/extension/src/ui/components/ErrorBoundaryFallbackWithCopyError.tsx
> +  } = useBackgroundSettingsValue<ISettingsStorage["privacyErrorReporting"]>(
Having to specify it in the type as well as in the function argument. Not a big deal.

2022-07-18 07:58 UTC, simonheys commented
> if you think you could do automatic source map uploads to sentry that would be great!

Sentry have cli tools for this, from memory it can be complicated to set up in CI, may be worth creating a separate Jira ticket and escalating if it becomes a pressing issue.

2022-07-20 08:55 UTC, janek26 approved these changes

2022-07-20 08:55 UTC, janek26 commented on packages/extension/src/ui/components/ErrorBoundaryFallbackWithCopyError.tsx
> +        "🚀 ~ file: ErrorBoundaryFallbackWithCopyError.tsx ~ line 118 ~ Sentry.withScope ~ eventId",
log

2022-07-20 08:55 UTC, janek26 commented on packages/extension/src/ui/services/useBackgroundSettingsValue.ts
> +  key: keyof ISettingsStorage,
please do:

```typescript
export const useBackgroundSettingsValue = <T extends ISettingsStorage, K extends keyof T>(
   key: K,
): T[K] => {
```

2022-07-20 08:55 UTC, janek26 commented on packages/extension/src/ui/components/ErrorBoundaryFallbackWithCopyError.tsx
> +  } = useBackgroundSettingsValue<ISettingsStorage["privacyErrorReporting"]>(
please clean this up, makes no sense to declare the type 2 times :D 
I added a comment to the useBackgroundSettingsValue file on how to do that

2022-07-20 08:55 UTC, janek26 commented on packages/extension/webpack.config.js
> +  devtool: "source-map",
can't we keep the above?

2022-07-20 08:55 UTC, janek26 requested changes
misclick

2022-07-20 10:42 UTC, dhruvkelawala commented on packages/extension/webpack.config.js
> +  devtool: "source-map",
Yep.. without `source-map`, Sentry can't use sourcemaps. It needs `sourceMappingUrl`. However, we can use "inline-source-map" for dev and disable Sentry logging for dev. I don't think so its needed anyways.

2022-07-20 10:43 UTC, dhruvkelawala commented on packages/extension/src/ui/components/ErrorBoundaryFallbackWithCopyError.tsx
> +        "🚀 ~ file: ErrorBoundaryFallbackWithCopyError.tsx ~ line 118 ~ Sentry.withScope ~ eventId",
Have left this here temporarily. Will remove before final merge. `eventId` helps debugging with sentry-cli

2022-07-21 16:25 UTC, simonheys commented on packages/extension/src/ui/services/useBackgroundSettingsValue.ts
> +) => {
Had to play around a bit as this is good learning for me too, what do you think?

A few changes together seem to get it working nicely, including changing the signatures of getSetting() etc.;

This gives the correct 'storedValue' state type
```
export const useBackgroundSettingsValue = <K extends keyof ISettingsStorage>(
  key: K,
) => {
  const [initialised, setInitialised] = useState<boolean>(false)
  const [storedValue, setStoredValue] = useState<ISettingsStorage[K]>()
```

Then can use the type e.g. here
```
const setValue = useCallback(
    async (value: ISettingsStorage[K]) => {
```

Same pattern in backgroundSettings
```
export const getSetting = async <K extends keyof ISettingsStorage>(
  key: K,
): Promise<ISettingsStorage[K]> => {

export const setSetting = async <K extends keyof ISettingsStorage>(
  key: K,
  value: ISettingsStorage[K],
) => {

export const removeSetting = async <K extends keyof ISettingsStorage>(
  key: K,
) => {
```

Then can simplify, e.g. this will know the return type from the key
```
const value = await getSetting(key)
```

2022-07-21 16:38 UTC, dhruvkelawala commented on packages/extension/src/ui/services/useBackgroundSettingsValue.ts
> +) => {
I wasted a lot of my time on this yesterday and potentially came out with a solution which didn't work. And we are going to change it to new storage type. i'll probably do it in other PR. Janek also agreed to it.

2022-07-21 16:39 UTC, dhruvkelawala commented on packages/extension/src/ui/services/useBackgroundSettingsValue.ts
> +) => {
If you agree to it, please approve :)

2022-07-21 16:45 UTC, simonheys commented on packages/extension/src/ui/services/useBackgroundSettingsValue.ts
> +) => {
IMO current state of these types is not good, it was cleaner and easier to follow before. We spend more time reading than writing code so legibility is paramount and is definitely not time wasted.

```
} = useBackgroundSettingsValue<ISettingsStorage["privacyShareAnalyticsData"]>(
    "privacyShareAnalyticsData",
  )
```

...needs to be like this to be legible:

```
} = useBackgroundSettingsValue(
    "privacyShareAnalyticsData",
  )
```

Let's defer to @janek26 to decide whether this PR or another one very soon after.

2022-07-21 16:51 UTC, dhruvkelawala commented on packages/extension/src/ui/services/useBackgroundSettingsValue.ts
> +) => {
It's waste of time just because we are going to change to Object storage type. That's why. Nothing else. Otherwise I also don't like the implementation currently.

2022-07-25 08:46 UTC, janek26 commented
closed in favor of https://github.com/argentlabs/argent-x/pull/993

2022-07-25 08:46 UTC, closed without merging